name: ds_purchase
description: "Purchase SectDev components for Flutter projects (https://sect.dev/). Currently supports Adapty only"
version: 1.0.3
homepage: https://github.com/al-tush/ds_purchase

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.0.0
  fimber: ^0.7.0
  firebase_analytics: '>=10.10.0 <12.0.0'
  ds_common: ^1.0.4
  ds_ads: ^1.0.2

  adapty_flutter: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.altush.ds_purchase
        pluginClass: DsPurchasePlugin
      ios:
        pluginClass: DsPurchasePlugin
